default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5433   # porta real do cluster
  username: angelocoelho
  password: postgres
  pool: 5

development:
  <<: *default
  database: clinic_development

test:
  <<: *default
  database: clinic_test

production:
  <<: *default
  database: clinic_production
  username: clinic
  password: postgres