name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint (RuboCop)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop -f github --parallel

  test:
    name: Tests (RSpec)
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: clinic_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres -d clinic_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/clinic_test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Prepare DB
        run: bin/rails db:prepare

      - name: Run RSpec
        run: bundle exec rspec --format documentation
